<?php

/* Contains data for dining halls. */

/* Array with dining hall names as keys,
 * arrays of lat, long as values */
$lat_long = array(
	"104west"					=> array(42.444124,-76.487482),
	"amit_bhatia_libe_cafe"				=> array(42.447902,-76.484284),
	"atrium_cafe"					=> array(42.445873,-76.483297),
	"bear_necessities"				=> array(42.455741,-76.477565),
	"bears_den"					=> array(42.446725,-76.485706),
	"becker_house_dining_room"			=> array(42.44825, -76.489547),
	"big_red_barn"					=> array(42.448478,-76.481034),
	"cafe_jennie"					=> array(42.44673, -76.484646),
	"carols_cafe"					=> array(42.453224,-76.479387),
	"cascadeli"					=> array(42.446499,-76.485599),
	"cascadeli_delivers"				=> array(42.446499,-76.485599),
	"cook_house_dining_room"			=> array(42.448937,-76.489584),
	"cornell_dairy_bar"				=> array(42.447576,-76.469929),
	"goldies"					=> array(42.450014,-76.481661),
	"green_dragon"					=> array(42.450912,-76.483979),
	"ivy_room"					=> array(42.446697,-76.485572),
	"jansens_dining_room,_bethe_house"		=> array(42.447243,-76.488742),
	"jansens_market"				=> array(42.446499,-76.487884),
	"keeton_house_dining_room"			=> array(42.446883,-76.489182),
	"marthas_cafe"					=> array(42.450133,-76.479145),
	"mattins_cafe"					=> array(42.444456,-76.482278),
	"north_star"					=> array(42.453515,-76.476061),
	"okenshields"					=> array(42.446451,-76.485668),
	"one_world_cafe"				=> array(42.444941,-76.485896),
	"risley_dining"					=> array(42.453228,-76.482106),
	"robert_purcell_marketplace_eatery"		=> array(42.455864,-76.477504),
	"rose_house_dining_room"			=> array(42.447821,-76.488791),
	"rustys"					=> array(42.447223,-76.482208),
	"synapsis_cafe"					=> array(42.446829,-76.477211),
	"trillium"					=> array(42.447979,-76.479124),
	"trillium_express"				=> array(42.447932,-76.479338),
	"west_side_express"				=> array(42.44699, -76.488544)
);

/* Array with dining hall names as keys,
 * "pretty" version of names as values */
$pretty_names = array(
	"104west"					=> "104West!",
	"amit_bhatia_libe_cafe"				=> "Amit Bhatia Libe Cafe",
	"atrium_cafe"					=> "Atrium Cafe",
	"bear_necessities"				=> "Bear Necessities",
	"bears_den"					=> "Bear's Den",
	"becker_house_dining_room"			=> "Becker House Dining Room",
	"big_red_barn"					=> "Big Red Barn",
	"cafe_jennie"					=> "Cafe Jennie",
	"carols_cafe"					=> "Carol's Cafe",
	"cascadeli"					=> "Cascadeli",
	"cascadeli_delivers"				=> "Cascadeli Delivers",
	"cook_house_dining_room"			=> "Cook House Dining Room",
	"cornell_dairy_bar"				=> "Cornell Dairy Bar",
	"goldies"					=> "Goldie's",
	"green_dragon"					=> "Green Dragon",
	"ivy_room"					=> "Ivy Room",
	"jansens_dining_room,_bethe_house"		=> "Jansen's Dining Room, Bethe House",
	"jansens_market"				=> "Jansen's Market",
	"keeton_house_dining_room"			=> "Keeton House Dining Room",
	"marthas_cafe"					=> "Martha's Cafe",
	"mattins_cafe"					=> "Mattin's Cafe",
	"north_star"					=> "North Star",
	"okenshields"					=> "Okenshields",
	"one_world_cafe"				=> "One World Cafe",
	"risley_dining"					=> "Risley Dining",
	"robert_purcell_marketplace_eatery"		=> "Robert Purcell Marketplace Eatery",
	"rose_house_dining_room"			=> "Rose House Dining Room",
	"rustys"					=> "Rusty's",
	"synapsis_cafe"					=> "Synapsis Cafe",
	"trillium"					=> "Trillium",
	"trillium_express"				=> "Trillium Express",
	"west_side_express"				=> "West Side Express"
);

/* Array with dining hall names as keys,
 * building names as values */
$buildings = array(
	"104west"					=> "West Ave",
	"amit_bhatia_libe_cafe"				=> "Olin Library",
	"atrium_cafe"					=> "Sage Hall",
	"bear_necessities"				=> "Robert Purcell Community Center",
	"bears_den"					=> "Willard Straight Hall",
	"becker_house_dining_room"			=> "Carl Becker House",
	"big_red_barn"					=> "Big Red Barn",
	"cafe_jennie"					=> "The Cornell Store",
	"carols_cafe"					=> "Balch Hall",
	"cascadeli"					=> "Willard Straight Hall",
	"cascadeli_delivers"				=> "Willard Straight Hall",
	"cook_house_dining_room"			=> "Alice Cook House",
	"cornell_dairy_bar"				=> "Stocking Hall",
	"goldies"					=> "Physical Sciences Building",
	"green_dragon"					=> "Sibley Hall",
	"ivy_room"					=> "Willard Straight Hall",
	"jansens_dining_room,_bethe_house"		=> "Hans Bethe House",
	"jansens_market"				=> "Noyes Community Recreation Center",
	"keeton_house_dining_room"			=> "William Keeton House",
	"marthas_cafe"					=> "Martha Van Rensselaer Hall",
	"mattins_cafe"					=> "Duffield Hall",
	"north_star"					=> "Appel Commons",
	"okenshields"					=> "Willard Straight Hall",
	"one_world_cafe"				=> "Anabel Taylor Hall",
	"risley_dining"					=> "Risley Hall",
	"robert_purcell_marketplace_eatery"		=> "Robert Purcell Community Center",
	"rose_house_dining_room"			=> "Flora Rose House",
	"rustys"					=> "Uris Hall",
	"synapsis_cafe"					=> "Weill Hall",
	"trillium"					=> "Kennedy Hall",
	"trillium_express"				=> "Kennedy Hall",
	"west_side_express"				=> "Hans Bethe House"
);

/* Array of "BRBs" or "AYCTE" */
$payment = array(
	"104west"					=> "All You Care To Eat",
	"amit_bhatia_libe_cafe"				=> "Big Red Bucks",
	"atrium_cafe"					=> "Big Red Bucks",
	"bear_necessities"				=> "Big Red Bucks",
	"bears_den"					=> "Big Red Bucks",
	"becker_house_dining_room"			=> "All You Care To Eat",
	"big_red_barn"					=> "Big Red Barn",
	"cafe_jennie"					=> "Big Red Bucks",
	"carols_cafe"					=> "Big Red Bucks",
	"cascadeli"					=> "Big Red Bucks",
	"cascadeli_delivers"				=> "Big Red Bucks",
	"cook_house_dining_room"			=> "All You Care To Eat",
	"cornell_dairy_bar"				=> "Big Red Bucks",
	"goldies"					=> "Big Red Bucks",
	"green_dragon"					=> "Big Red Bucks",
	"ivy_room"					=> "Big Red Bucks",
	"jansens_dining_room,_bethe_house"		=> "All You Care To Eat",
	"jansens_market"				=> "Big Red Bucks",
	"keeton_house_dining_room"			=> "All You Care To Eat",
	"marthas_cafe"					=> "Big Red Bucks",
	"mattins_cafe"					=> "Big Red Bucks",
	"north_star"					=> "All You Care To Eat",
	"okenshields"					=> "All You Care To Eat",
	"one_world_cafe"				=> "Big Red Bucks",
	"risley_dining"					=> "All You Care To Eat",
	"robert_purcell_marketplace_eatery"		=> "All You Care To Eat",
	"rose_house_dining_room"			=> "All You Care To Eat",
	"rustys"					=> "Big Red Bucks",
	"synapsis_cafe"					=> "Big Red Bucks",
	"trillium"					=> "Big Red Bucks",
	"trillium_express"				=> "Big Red Bucks",
	"west_side_express"				=> "Hans Bethe House"
);

?>